pipeline{
    agent { label 'jenkins-agent'}
    stages {
        stage("clone git app"){
            steps{
                git url: "https://github.com/MAHIRE-7/bookshelf.git", branch: "main"
            }
        }
        
        stage("Build Container"){
            steps{
                sh "docker build -t manodayahire/bookshelf:latest ."
            }
        }
        stage("Push Container"){
            steps{
                withCredentials([usernamePassword(credentialsId: 'dockerCred', 
                                                 usernameVariable: 'USER', 
                                                 passwordVariable: 'PASS')]){
                
                sh "docker login -u $USER -p $PASS "
                sh "docker build -t manodayahire/bookshelf:latest ."}
            }
        }

        stage("Run Container"){
            steps{
                sh "docker-compose up -d"
            }
        }
        
        
    }
}