pipeline{
    agent {label 'jenkins-agent'}
     environment {
        IMAGE = "manodayahire/wordtopdf"
        VERSION = "${BUILD_NUMBER}"
    }
    
    
    stages{
        // GIT CODE CLONE
        stage("Code Clone"){
            steps{
                git url: "https://github.com/MAHIRE-7/wordtopdf.git", branch: "main"
            }
        }

        // OWASP CVE check
      stage("OWASP Dependency Scan") {
            steps {
                dependencyCheck(
                    odcInstallation: 'owasp',
                    additionalArguments: '''
                    --scan .
                    --format HTML
                    --disableAssembly
                    --failOnCVSS 11
                    '''
                )
            }
        }
        
        //OWASP Report generation
        stage("OWASP Report") {
            steps {
                archiveArtifacts artifacts: '**/dependency-check-report.html', fingerprint: true
            }
        }
        //SonarQube Scan
         stage("SonarQube Scan") {
            steps {
                withSonarQubeEnv('sonarqube') {
                sh "sonar-scanner -Dsonar.projectKey=wordtopdf -Dsonar.sources=."
                                            }
            }
        }
        // SonarQube QualityGates Scan
        stage("Quality Gate") {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        //Docker Build
        stage("Docker Build"){
            steps{
                sh "docker build -t $IMAGE:$VERSION ."
            }
        }

        // Docker Image Push to Dockerhub
        stage("Docker Push"){
            steps{
                withCredentials([usernamePassword(credentialsId: 'dockerCredentials', 
                                                 usernameVariable: 'USER', 
                                                 passwordVariable: 'PASS')]){
                sh "docker login -u ${USER} -p ${PASS} "
                sh "docker push $IMAGE:$VERSION"
                                                 }
            }
        }

        // Docker Image cleanup from local
        stage("Image Cleanup"){
            steps{

                sh "DEL_VERSION = $((VERSION-2))"
                sh "docker rmi $IMAGE:$DEL_VERSION"
            }
        }

        // K8s Tag Update
        stage("K8S Tag Update"){
            steps{
            withCredentials([usernamePassword(credentialsId: 'gitCredentials', 
                                                 usernameVariable: 'GIT_USER', 
                                                 passwordVariable: 'GIT_PASS')]){
                                                     sh""" 
                                                      echo "Updating Kubernetes manifest with new image tag"
                                                        
            git checkout release
            sed -i 's|image: .*|image: ${IMAGE}:${VERSION}|' k8s/app-deployment.yml

            git config user.email "manodayahire786@gmail.com"
            git config user.name "Manoday Ahire"

            git add k8s/app-deployment.yml
            git commit -m  "K8s Image Tag Updated With $IMAGE:$VERSION "

            git push https://${GIT_USER}:${GIT_PASS}@github.com/MAHIRE-7/wordtopdf HEAD:release
                                                     """
                                                 }
            }
        }
        }
    }
